import json
import re
import logging

logger = logging.getLogger(__name__)


def clean_and_parse_json(text: str) -> dict:
    """Robustly cleans and parses JSON responses from LLMs, handling markdown blocks,
    deepseek/qwen reasoning tags (<think>...</think>), unescaped control characters,
    trailing commas, unclosed brackets, and partial truncation."""
    if not text or not text.strip():
        logger.warning("clean_and_parse_json received empty text. Returning empty dict.")
        return {}

    # Strip thinking / reasoning tags commonly generated by DeepSeek R1 and reasoning models
    text = re.sub(r"<think>[\s\S]*?</think>", "", text, flags=re.IGNORECASE)
    text = re.sub(r"<thought>[\s\S]*?</thought>", "", text, flags=re.IGNORECASE)

    # Strip markdown code block wrappers
    text = re.sub(r"```(?:json)?", "", text, flags=re.IGNORECASE)
    text = text.replace("```", "")
    text = text.strip()

    # Direct parse attempt
    try:
        return json.loads(text, strict=False)
    except Exception:
        pass

    # Find opening and closing braces
    start = text.find("{")
    end = text.rfind("}")

    if start == -1:
        # If no JSON braces exist, attempt heuristic line-by-line key:value extraction
        extracted = {}
        for line in text.splitlines():
            line = line.strip()
            if ":" in line and not line.startswith(("-", "#", "*")):
                k, v = line.split(":", 1)
                k = k.strip().strip('"').strip("'").lower().replace(" ", "_")
                v = v.strip().strip('"').strip("'")
                if k and v:
                    extracted[k] = v
        if extracted:
            return extracted

        logger.warning("LLM response did not contain JSON braces. Falling back to empty object.")
        return {}

    if end == -1 or end <= start:
        json_str = text[start:] + "}"
    else:
        json_str = text[start:end + 1]

    # Normalize Python literals if LLM printed Python dict instead of JSON
    json_str = re.sub(r"\bNone\b", "null", json_str)
    json_str = re.sub(r"\bTrue\b", "true", json_str)
    json_str = re.sub(r"\bFalse\b", "false", json_str)

    try:
        return json.loads(json_str, strict=False)
    except Exception:
        pass

    # Trailing commas cleanup
    json_str = re.sub(r",\s*([}\]])", r"\1", json_str)
    try:
        return json.loads(json_str, strict=False)
    except Exception:
        pass

    # Unterminated string & bracket balance repair
    if json_str.count('"') % 2 != 0:
        json_str += '"'
    if json_str.count("[") > json_str.count("]"):
        json_str += "]" * (json_str.count("[") - json_str.count("]"))
    if json_str.count("{") > json_str.count("}"):
        json_str += "}" * (json_str.count("{") - json_str.count("}"))

    try:
        return json.loads(json_str, strict=False)
    except Exception as exc:
        logger.warning("Could not parse JSON even after repairs: %s. Returning empty dict.", exc)
        return {}
